/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Interface.java to edit this template
 */
package psproject_v5.domain;

import java.io.Serializable;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author aleks
 */
public interface IEntity extends Serializable{    
    
    String getInsertQuery();//add
    String getSelectQuery();//getAll, getAllFilter
    String getUpdateQuery();//update
    String getWhereCondition();//getAll, getAllFilter, update, delete
    IEntity getDomainObjectFromRS(ResultSet rs) throws SQLException;//getAll, getAllFilter    
    void fillPreparedStatement(PreparedStatement ps) throws SQLException;//add, update
    
    Object getId();
    void setId(Object id);//add--- svaka klasa svakako ima ovo
    default Object getAutoGeneratedID(ResultSet rs) throws SQLException{
        return rs.getLong(1);
    }
    
    /**
     *
     * @throws Exception
     */
    void checkSimpleValueRestrictions() throws Exception;
    void checkComplexValueRestrictions() throws Exception;
    void checkStructuralRestrictions() throws Exception;
    
}
